<a href="https://colab.research.google.com/github/trungthanhzz/Hearts/blob/main/CNN%2BPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cơ bản về Pytorch

In [ ]:
!pip install torch torchvision


**Cơ bản về PyTorch**

1. **Tensor**

In [ ]:
import torch.nn as nn
import torch.nn.functional as F
from __future__ import print_function
import torch

# Khởi tạo một ma trận rỗng

x = torch.empty(5, 3)
print(x)


tensor([[1.5766e-19, 1.0256e-08, 1.0501e-05],
        [3.1129e+12, 4.3356e-08, 1.6412e-07],
        [2.6407e-06, 1.2752e+16, 2.1707e-18],
        [7.0952e+22, 1.7748e+28, 1.8176e+31],
        [7.2708e+31, 5.0778e+31, 3.2608e-12]])


In [ ]:
#Khởi tạo ma trận ngẫu nhiên
x = torch.rand(5, 3)
print(x)



tensor([[0.5215, 0.3804, 0.8512],
        [0.8595, 0.8815, 0.2180],
        [0.3790, 0.2975, 0.4332],
        [0.7931, 0.9075, 0.4202],
        [0.7860, 0.6907, 0.3311]])


In [ ]:
#Khởi tạo ma trận với kiểu dữ liệu long
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
#Khởi tạo ma trận từ list
x = torch.tensor([5,3.5])
print(x)

tensor([5.0000, 3.5000])


In [ ]:
# Khởi tạo ma trận có các thuộc tính tương tự như của một ma trận sẵn có. Chẳng hạn như shape. Trừ khi thuộc tính mới được đưa vào override thuộc tính cũ.

x = x.new_ones(5, 3, dtype = torch.double)
print(x)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [ ]:
x = torch.randn_like(x, dtype = torch.float) #override dtype
# Ma trận mới được khởi tạo ngẫu nhiên có shape tương tự như ma trận cũ, dtype được override.
print(x)


tensor([[-0.3712,  0.3124,  1.1631],
        [ 0.5121,  0.1689,  0.0909],
        [-1.2722, -0.7893,  0.1233],
        [ 1.3247,  0.8948, -0.3499],
        [ 1.5640, -2.1661,  0.1461]])


2. **Operations**


# Xây dựng mạng CNN

Xây dựng mạng neural network sẽ trải qua các bước sau:

- Xây dựng kiến trúc mạng nơ ron.
- Phân chia dữ liệu train, test.
- Xác định phương pháp optimization để cập nhật gradient descent và hàm loss function.
- Huấn luyện model.
- Hậu kiểm model.


Để xây dựng mạng neural chúng ta sẽ kế thừa object `nn.Module`. Object này sẽ cho phép thực hiện quá trình lan truyền thuận và lan truyền ngược thông qua 2 hàm `forward()` và `backward()`.



In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
  def __init__(self):
    super(Net,self).__init__()
    # 1 kênh đầu vào, 6 kênh đầu ra, tích chập 3x3
    # kernel
    # conv2d (input chanels, output chanels, kernel size)
    self.conv1 = nn.Conv2d(1, 6, 3)
    self.conv2 = nn.Conv2d(6, 16, 3)
    # an affine operation: y = Wx + b
    self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
    self.fc2 = nn.Linear(120, 84)
    self.fc3 = nn.Linear(84, 10)

  def forward(self, x):
    # Max pooling over a (2, 2) window
    x = F.max_pool2d(F.relu(self.conv1(x)), (2,2))
    # If the size is a square you can only specify a single number
    x = F.max_pool2d(F.relu(self.conv2(x)), 2)
    x = x.view(-1, self.num_flat_features(x))
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    return x

  def num_flat_features(self, x):
    size = x.size()[1:]  # all dimensions except the batch dimension
    num_features = 1
    for s in size:
      num_features *= s
    return num_features

net = Net()
print(net)
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

net.zero_grad()
out.backward(torch.randn(1, 10))






Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)
tensor([[ 0.1263,  0.0081, -0.0321,  0.1126, -0.0316, -0.1250,  0.1947,  0.0579,
          0.0462,  0.0331]], grad_fn=<AddmmBackward0>)


# Mnist Dataset


Mnist là dữ liệu số viết tay